USE [master]
GO

/****** Object:  Database [kuzando]    Script Date: 05/06/2010 01:43:53 ******/
CREATE DATABASE [kuzando] ON  PRIMARY 
( NAME = N'kuzando', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\kuzando.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'kuzando_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\kuzando_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [kuzando] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [kuzando].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [kuzando] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [kuzando] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [kuzando] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [kuzando] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [kuzando] SET ARITHABORT OFF 
GO

ALTER DATABASE [kuzando] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [kuzando] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [kuzando] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [kuzando] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [kuzando] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [kuzando] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [kuzando] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [kuzando] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [kuzando] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [kuzando] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [kuzando] SET  DISABLE_BROKER 
GO

ALTER DATABASE [kuzando] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [kuzando] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [kuzando] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [kuzando] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [kuzando] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [kuzando] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [kuzando] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [kuzando] SET  READ_WRITE 
GO

ALTER DATABASE [kuzando] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [kuzando] SET  MULTI_USER 
GO

ALTER DATABASE [kuzando] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [kuzando] SET DB_CHAINING OFF 
GO

